# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=80)),
                ('currency', models.CharField(max_length=40)),
                ('currency_symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=40)),
                ('property_name', models.CharField(max_length=80)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('days', models.IntegerField()),
                ('home_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('home_age', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('items', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Real_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_state', models.CharField(max_length=80)),
                ('site', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Property_Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='real_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Real_State'),
        ),
    ]
